name: Build and Test Node App

on:
  push:
    branches: [ main, staging, dev ]

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Prod' || github.ref == 'refs/heads/staging' && 'Staging' || 'Dev' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ github.ref == 'refs/heads/main' && '18' || github.ref == 'refs/heads/staging' && '16' || '14' }}

    - name: Install dependencies
      run: echo " ${{ vars.STATUS }} "
      run: npm install --save-dev jest supertest express dotenv --only=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    - name: Run tests
      run: npm test