name: Build and Test Node App

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --save-dev jest supertest express

    - name: Run tests
      run: npm test